version: '3'
services:
  # for data generation
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4 
  #   ports:
  #     - 9200:9200
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.type=single-node"
  #   volumes:
  #     - ./elasticsearch/es-data/data/:/usr/share/elasticsearch/data
  elasticsearch:
    build: 
       context: .
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4       
    ports:
      - 5601:5601
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
